export const environment = {
  production: true,
  BASE_URL:"/ltapp",
  AUTH_API:"/authenticate",
  LOGOUT_API:"/logout",
  FETCH_USER_ROLES_API:"/authenticate",
  SLAREPORTS_API:"/sladashboard/fetchSlaReports",
  SLAREPORTS_FILTER_API:"/sladashboard/fetchSlaReportswithfilter",
  SLAREPORTS_DOWNLOAD_API:"/sladashboard/download",
  USER_DISCOM_DATA_API:"/access/fetchStateAndDiscomForUser",
  FETCH_CONFIG_CODE_LIST_API:"/common/code",
  FETCH_CONFIG_CODE_LIST_SUBTYPE_API:"/common/findcodewithsubtype",
  FETCH_ROLES_API:"/roles/fetchRoles",
  FETCH_ALL_ROLES_FOR_TYPE_API:"/roles/fetchAllRoles",
  FETCH_ROLE_DETAILS_API:"/roles/roledata",
  FETCH_ROLES_WITH_FILTER_API:"/roles/fetchRoleswithfilter",
  FETCH_All_MODULES_API:"/access/moduleslist",
  FETCH_MODULE_ACCESS_API:"/access/modulespermission",
  SAVE_ROLE_API:"/roles/save",
  CREATE_ROLE_API:"/roles/create",
  DELETE_ROLE_API:"/roles/delete",
  FETCH_USERS_API:"/user/getuserslist",
  FETCH_USERS_WITH_FILTER_API:"/user/getuserslistwithfilter",
  FETCH_DISCOMS_IN_STATES_API:"/common/discominstate",
  FETCH_ALL_STATES_API:"/common/discomstatelist",
  FETCH_USER_DATA_API:"/user/getuserdata",
  CHECK_USER_NAME_API:"/user/checkusername",
  SAVE_USER_API:"/user/save",
  CREATE_USER_API:"/user/create",
  FETCH_APPROVER_API:"/approval/list",
  FETCH_APPROVER_WITH_FILTER_API:"/approval/find",
  DELETE_APPROVER_API:"/approval/delete",
  FIND_APPROVER_BY_NAME_API:"/approval/getapprover",
  SAVE_APPROVER_API:"/approval/saveapprover",
  CREATE_APPROVER_API:"/approval/createapprover",

  UAM_REGISTER_API:"/uam/register",
  UAM_VIEW_STATUS_API:"/uam/getid",
  UAM_VIEW_DETAILS_API:"/uam/reference",
  UAM_FETCH_APPLICATIONS_API:"/uam/getall",
  UAM_FETCH_APPLICATIONSWITH_FILTER_API:"/uam/getallwithfilter",
  UAM_APPROVE_API:"/uam/approval",
  UAM_VALID_STATUS_API:"/uam/getstatuslist",
  UAM_COMPLETE_API:"/uam/completeapplication",
  UAM_GET_NEXT_APPROVER_API:"/uam/getnextapprover",
};
export const roleType = {
  ADMIN:"ADMIN",
  MANAGER:"MANAGER",
  VIEWER:"VIEWER",
};
export const roleConfig = {
  RoleCreation:"SRC",
  UserCreation:"SUC",
  ApproverCreation:"APPUC",
};
